version = "1.0"
name = "telegram-bot"
description = "Telegram Bot on Railway"

[env]
  TELEGRAM_BOT_TOKEN = "6690495865:AAG8GZOuyMaYBqyVF4QAP_GBkugEi0N4Sfg"
  BOT_USERNAME = "@LearntopiaBot"

[services]
  [services.default]
  memory = "512M"
  command = "python main.py"